class HelloWorld {
    
    public static void main(String[] args) {
        
    
     String nomeproduto;
     double precoproduto;
     String marcaproduto;
     Integer quantidadeproduto;
     String descricaoproduto;
     String nomeproduto2;
     Integer numeroProduto;
     double precoproduto2;
     Integer estoquedisponivel;
     Integer totaldeprodutos;
        
        
        
        
        
    }

}
